---
- name: Create directory for monitoring
  file:
    path: /usr/local/share/dodasts/monitoring
    state: directory
    mode: 0755

- name: Create directory for grafana
  file:
    path: /usr/local/share/dodasts/monitoring/grafana
    state: directory
    mode: 0755

- name: Create grafana configs
  copy:
    src: "{{ role_path }}/files/grafana"
    dest: /usr/local/share/dodasts/monitoring
    directory_mode: 0755

- name: Add execution permission to get_client
  file:
    path: /usr/local/share/dodasts/monitoring/grafana/utils/get_client
    mode: u+rwx

- name: download dodas-IAMClientRec
  git:
    repo: "https://github.com/DODAS-TS/dodas-IAMClientRec.git"
    dest: /usr/local/share/dodasts/dodas-IAMClientRec
    force: yes

- name: compile dodas-IAMClientRec
  shell:
    cmd: go build
    chdir: /usr/local/share/dodasts/dodas-IAMClientRec

- name: link executable dodas-IAMClientRec
  shell:
    cmd: ln -s /usr/local/share/dodasts/dodas-IAMClientRec/dodas-IAMClientRec /usr/local/bin/dodas-IAMClientRec
    creates: /usr/local/bin/dodas-IAMClientRec

- name: Create grafana config
  template:
    src: grafana.ini.j2
    dest: /usr/local/share/dodasts/monitoring/grafana/config/custom.ini

- name: get client id and secret
  shell:
    cmd: |
      /usr/local/share/dodasts/monitoring/grafana/utils/get_client {{ monitoring_iam_url }} {{ monitoring_server_ip }} {{ service_grafana_port }}
  when: service_grafana_client_id == "CLIENT_ID" and service_grafana_client_secret == "CLIENT_SECRET"

- name: let grafana to create admin
  set_fact:
    key_values: "yes"
    service_grafana_disable_admin_creation: false
  when: (service_grafana_admin_user|length > 0) and (service_grafana_admin_password|length > 0)

- name: prepare variables for monitoring
  set_fact:
    key_value: "yes"
    grafana_service: |
      grafana:
          image: dodasts/monitoring-grafana:v1.0.1-monitoring
          container_name: monitoring_grafana
          depends_on:
            - prometheus
          restart: unless-stopped
          command:
            - "-config"
            - "/opt/grafana/custom.ini"
          ports:
            - {{ service_grafana_port }}:{{ service_grafana_port }}
          volumes:
            - /usr/local/share/dodasts/certs/grafana:/usr/local/share/dodasts/certs/grafana
            - /usr/local/share/dodasts/monitoring/grafana/config:/opt/grafana/
            - /usr/local/share/dodasts/monitoring/grafana/config/provisioning:/etc/grafana/provisioning
            - /usr/local/share/dodasts/monitoring/grafana/dash_models:/opt/dash_models
          environment:
            - GF_SECURITY_ADMIN_USER={{ service_grafana_admin_user }}
            - GF_SECURITY_ADMIN_PASSWORD={{ service_grafana_admin_password }}
            - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION={{ service_grafana_disable_admin_creation }}
            - GF_USERS_ALLOW_SIGN_UP=false
