#!/usr/bin/env python3
import subprocess
from sys import argv


def main():
    client = subprocess.check_output(
        f"IAM_INSTANCE={argv[1]} OAUTH_CALLBACK=https://{argv[2]}:{argv[3]}/login/generic_oauth dodas-IAMClientRec ml-client",
        shell=True,
        encoding="utf-8",
    )
    lines = [line for line in client.split("\n") if line]
    # Remove ASCII escape chars
    lines = [line.replace("\x1b[0m", "").replace("\x1b[32m", "") for line in lines]

    with open(
        "/usr/local/share/dodasts/monitoring/grafana/config/custom.ini"
    ) as cur_config:
        cur_config_string = cur_config.read()

    cur_config_string = cur_config_string.replace(
        "CLIENT_ID", f'"{lines[-2].strip()}"'
    ).replace("CLIENT_SECRET", f'"{lines[-1].strip()}"')

    with open(
        "/usr/local/share/dodasts/monitoring/grafana/config/custom.ini", "w"
    ) as cur_config:
        cur_config.write(cur_config_string)


if __name__ == "__main__":
    main()
